version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gradle-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "com.velocitypowered:velocity-api"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
