# These are supported funding model platforms

github: [HanielCota]
ko_fi: # Replace with your ko-fi username
liberapay: # Replace with your liberapay username
patreon: # Replace with your Patreon username
custom: ["https://www.paypal.me/HanielCota"]