name: Config
description: Configuration-related issue or question
title: "[CONFIG] "
labels: ["config"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your configuration issue or question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context, code snippets, or environment details
    validations:
      required: false
